apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: create-notebook-template
  title: Create Notebook Template
  description: Template for new notebook creation.
spec:
  owner: xwing-libra
  type: notebook

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Provide Workflow specification
      required:
        - name
        - workspace
        - gcpProject
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the notebook
          ui:field: EntityNamePicker
          ui:autofocus: true
        workspace:
          title: Workspace
          type: string
          description: Workspace context
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System
        gcpProject:
          title: GCP project
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Resource
              spec.type: gcp-project
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOrganizations:
              - data-console
            allowedOwners:
              - data-console
            allowedRepos:
              - workshops-state
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN


  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          workspace: ${{ parameters.workspace }}
          gcpProject: ${{ parameters.gcpProject }}
          user: ${{ user.entity.metadata.name }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: cloud-project-${{ parameters.name }}
        title: ":sparkles: Create notebook ${{ parameters.name }}"
        description: Create new workspace ${{ parameters.name }}
        targetPath: ${{ parameters.workspace | parseEntityRef | pick('name')  }}/${{ parameters.name }}
        commintMessage: ":sparkles: Create notebook ${{ parameters.name }}"
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/data-console/workshops-state
        catalogInfoPath: "/blob/main/${{ parameters.workspace | parseEntityRef | pick('name') }}/${{ parameters.name }}/catalog-info.yaml"
        optional: true

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: PR
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
