---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description | dump }}
  annotations:
    allegro.com/resource-type: "gcp-cloud-composer"
  labels:
    allegro.com/sc-id: "${{ values.scId }}"
spec:
  type: scheduler
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.workspace }}
  dependsOn:
    - ${{ values.cloudProject }}{% for env in values.environments %}
    - resource:default/${{ values.name }}-${{ env }}{% endfor %}{% for env in values.environments %}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-${{ env }}
  description: "${{ values.description }} ${{ env }} environment"
  labels:
    allegro.com/sc-id: "${{ values.scId }}"
    allegro.com/environment: "${{ env }}"
spec:
  type: gcp-cloud-composer
  owner: ${{ values.owner }}
  system: ${{ values.workspace }}
  dependsOn:
    - resource:${{ values.cloudProject | parseEntityRef | pick("name") }}-${{ env }}
  dependencyOf:
    - component:default/${{ values.name }}{% endfor %} }}
