---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description | dump }}
  labels:
    allegro.com/sc-id: "${{ values.scId }}"
spec:
  type: workflow
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.workspace }}
  scheduler: ${{ values.scheduler }}
  dependsOn:
    - ${{ values.scheduler }}